"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import type { Dashboard } from "./DashboardNoivos";
type Auditoria={id:string;ator:string;perfil:string;acao:string;entidade:string;criado_em:string;detalhes?:{id?:string;campos_alterados?:string[];antes?:Record<string,unknown>|null;depois?:Record<string,unknown>|null}};
type Controle={auditoria:Auditoria[];falhas_webhook:Array<{id:string;pagamento_id:string|null;etapa:string;mensagem:string;resolvida:boolean;criado_em:string}>;reservas:Array<Record<string,unknown>>;presentes:Array<Record<string,unknown>>};
const salvar=(wb:XLSX.WorkBook,nome:string)=>XLSX.writeFile(wb,nome,{compression:true});
export function ControlesAdministrativos({dados,codigo,voltar}:{dados:Dashboard;codigo:string;voltar:()=>void}){
 const [controle,setControle]=useState<Controle>({auditoria:[],falhas_webhook:[],reservas:[],presentes:[]}),[aviso,setAviso]=useState(""),[carregando,setCarregando]=useState(true);
 const carregar=useCallback(async()=>{setCarregando(true);const r=await fetch("/api/convite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"controles_administrativos",codigo})});const d=await r.json();setCarregando(false);if(r.ok)setControle(d);else setAviso(d.error||"Não foi possível carregar os controles.")},[codigo]);
 useEffect(()=>{const timer=window.setTimeout(()=>void carregar(),0);return()=>window.clearTimeout(timer)},[carregar]);
 const resumo=useMemo(()=>{const c=dados.convidados.filter(p=>p.resposta==="sim");return{confirmados:c.length,criancas:c.filter(p=>p.crianca).length,cortejo:c.filter(p=>p.nivel_acesso>=2||Boolean(p.funcao&&p.funcao!=="Convidado")).length,adultos:c.filter(p=>!p.crianca).length}},[dados.convidados]);
 function backup(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(dados.convidados),"Convidados e confirmações");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(controle.presentes),"Presentes");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(controle.reservas),"Assinaturas e pagamentos");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(controle.auditoria),"Auditoria");salvar(wb,`backup-casamento-${new Date().toISOString().slice(0,10)}.xlsx`)}
 function modelos(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Nome:"Maria Silva",Grupo:"Família Silva",Função:"Convidado",Origem:"Ambos"}]),"Modelo convidados");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Nome:"Jogo de jantar",Categoria:"Cozinha",Valor:350,"Links de fotos":"https://exemplo.com/foto.jpg",Descrição:"Opcional",Quantidade:1}]),"Modelo presentes");salvar(wb,"modelos-importacao-casamento.xlsx")}
 async function anonimizar(){if(!confirm("Excluir permanentemente todos os CPFs armazenados? Os dados não poderão ser recuperados."))return;const r=await fetch("/api/convite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"anonimizar_cpfs",codigo})});const d=await r.json();setAviso(r.ok?`${d.alterados} registro(s) de CPF foram anonimizados.`:d.error);if(r.ok)void carregar()}
 async function resolver(id:string){await fetch("/api/convite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"resolver_falha_webhook",codigo,dados:{id}})});void carregar()}
 return <div className="panel admin-page"><button className="back-link" onClick={voltar}>← Voltar à visão geral</button><p className="eyebrow">Administração e segurança</p><h1>Controles administrativos</h1>{aviso&&<p className="success-note">{aviso}</p>}
 <section className="control-section"><h2>Verificação pré-evento</h2><div className="metric-grid"><article><span>Confirmados</span><b>{resumo.confirmados}</b></article><article><span>Adultos</span><b>{resumo.adultos}</b></article><article><span>Crianças</span><b>{resumo.criancas}</b></article><article><span>Cortejo</span><b>{resumo.cortejo}</b></article></div></section>
 <section className="control-section"><h2>Backup e modelos</h2><div className="admin-actions"><button className="primary" onClick={backup} disabled={carregando}>Exportar backup completo</button><button className="secondary" onClick={modelos}>Baixar modelos de planilhas</button></div><small>Inclui convidados, confirmações, presentes, assinaturas, pagamentos e auditoria.</small></section>
 <section className="control-section danger-zone"><h2>Retenção de CPF</h2><p>Use após o encerramento do período fiscal definido pela administração.</p><button className="danger" onClick={anonimizar}>Excluir/anonimizar todos os CPFs</button></section>
 <section className="control-section"><h2>Alertas do Mercado Pago</h2>{!controle.falhas_webhook.filter(f=>!f.resolvida).length?<p>Nenhuma falha pendente.</p>:controle.falhas_webhook.filter(f=>!f.resolvida).map(f=><article className="alert-row" key={f.id}><div><b>{f.etapa}</b><small>{new Date(f.criado_em).toLocaleString("pt-BR")} · pagamento {f.pagamento_id||"não identificado"}</small><p>{f.mensagem}</p></div><button onClick={()=>resolver(f.id)}>Marcar resolvida</button></article>)}</section>
 <section className="control-section"><h2>Registro de auditoria</h2><p className="section-help">Abra um registro para comparar os valores anteriores e posteriores. Dados sensíveis aparecem como protegidos.</p>{!controle.auditoria.length?<p>{carregando?"Carregando...":"Nenhuma alteração registrada após a ativação."}</p>:<div className="audit-list">{controle.auditoria.map(a=>{const campos=a.detalhes?.campos_alterados||[];return <details className="audit-entry" key={a.id}><summary><b>{a.acao.replaceAll("_"," ")}</b><span>{a.entidade} · {a.ator}</span><small>{new Date(a.criado_em).toLocaleString("pt-BR")}</small></summary><div className="audit-details">{a.detalhes?.id&&<p><b>Registro:</b> {a.detalhes.id}</p>}<p><b>Campos alterados:</b> {campos.length?campos.join(", "):"registro antigo, sem comparação disponível"}</p>{(a.detalhes?.antes!==undefined||a.detalhes?.depois!==undefined)&&<div className="audit-compare"><div><h3>Antes</h3><pre>{a.detalhes?.antes?JSON.stringify(a.detalhes.antes,null,2):"—"}</pre></div><div><h3>Depois</h3><pre>{a.detalhes?.depois?JSON.stringify(a.detalhes.depois,null,2):"—"}</pre></div></div>}</div></details>})}</div>}</section></div>
}
