"use client";
const manuais:Record<string,{titulo:string;abertura:string;itens:Array<[string,string]>}>={
 padrinhos:{titulo:"Manual dos Padrinhos",abertura:"Vocês foram escolhidos para testemunhar e apoiar esta nova família.",itens:[["Antes do dia","Acompanhem os comunicados e reservem toda a noite para celebrar conosco."],["Chegada","Cheguem com antecedência e procurem a equipe de assessoria."],["Durante a cerimônia","A assessoria indicará a formação, a entrada e os lugares reservados."],["Apoio aos noivos","Estejam disponíveis, tranquilos e presentes nos momentos importantes."]]},
 demoiseles:{titulo:"Manual das Demoiselles",abertura:"Sua presença próxima à noiva torna este momento ainda mais especial.",itens:[["Preparação","Acompanhem os avisos sobre horários e encontro no dia."],["Chegada","Apresentem-se à assessoria com antecedência."],["Cerimônia","A equipe orientará a ordem de entrada e os lugares."],["Celebração","Ajudem a acolher, celebrar e manter o clima leve."]]},
 "amigos-do-noivo":{titulo:"Manual dos Amigos do Noivo",abertura:"Vocês fazem parte da história do noivo e terão um papel especial na celebração.",itens:[["Organização","Mantenham o grupo atento aos comunicados oficiais."],["Pontualidade","Cheguem no horário indicado e procurem a assessoria."],["Apoio","Ajudem o noivo nos momentos de preparação e transição."],["Celebração","Participem com alegria, respeito e atenção às orientações."]]},
 criancas:{titulo:"Manual das Crianças",abertura:"Pajens e daminhas terão uma participação delicada e muito querida.",itens:[["Para os responsáveis","Acompanhem todos os ensaios, horários e orientações."],["Chegada","Cheguem cedo para que a criança conheça o espaço com calma."],["Entrada","A assessoria explicará o trajeto e acompanhará a formação."],["Bem-estar","Respeitem o ritmo da criança; acolhimento vem antes da performance."]]}
};
export function ManualFuncao({codigos}:{codigos:string[]}){return <div className="panel manuals"><p className="eyebrow">Orientações do cortejo</p><h1>Manuais da sua função</h1><p>Estas são orientações gerais. Horários, vestimentas e regras específicas serão adicionados depois.</p>
 {codigos.map(c=>{const m=manuais[c];return m?<section key={c} className="manual-section"><h2>{m.titulo}</h2><p>{m.abertura}</p><div className="instruction-grid">{m.itens.map(([t,x],i)=><article key={t}><span>{i+1}</span><b>{t}</b><p>{x}</p></article>)}</div></section>:null})}</div>}
